### PR TITLE
Fix typo decription => description

### PR DESCRIPTION
**Pull request by alagoutte**

### CODE REVIEW

**Comment by tchiapuziowong** [comment]
Hi @alagoutte thank you for finding these errors! Could you please open another request to merge to the public-devel branch? Please see our [CONTRIBUTING.md](https://github.com/aruba/aruba-ansible-modules/blob/master/CONTRIBUTING.md) for any further contribution guidelines.

**Comment by alagoutte** [comment]
@tchiapuziowong there is no public-devel branch on this repo...

**Comment by tchiapuziowong** [comment]
@alagoutte apologies it was accidentally deleted by another user, I've re-created the branch public-devel, please open the review when you're ready! Thanks!

**Comment by alagoutte** [comment]
Done on PR #42 (the response of everythings ;-) )

**Comment by tchiapuziowong** [comment]
Haha thank you!! Merged!

**Pull request merged**
