### PR TITLE
Arubaos controller modules improvements

### PR DESCRIPTION
**Pull request by sachaboudjema**
# New ArubaOS controller modules

This PR refactors the ArubaOS controller modules.
It adds new modules with extended features while being backwards compatible with existing module.

* Install script updated
* Module doc updated
* Example playbooks updated
* All modules tested successfully

## List of modules

* **arubaos_controller_config**: Backward compatibility with playbooks based on the current module
* **arubaos_get**: Executes GET operations on API objects
* **arubaos_set**: Add, modify or delete configuration
* **arubaos_facts**: Populates `ansible_facts` with sys_info details about the system to which the query is being sent
* **arubaos_config**: Queries full or partial configuration of a particular configuration node.
* **arubaos_writememory**: Executes a show command on the controller and returns structured data when supported
* **arubaos_showcommand**: Commits the pending configuration (if any) on the specified node

### General

* Backwards compatibility with playbooks based on the current module
* Module_utils provides easy to reuse methods to interact with API
* Implementation focused on idempotency
* Follows Ansible module implementation best practices
* Provides environment var fallback for frequently used arguments to avoid having to repeat them on each module call

### arubaos_get

* Implements all get modifiers (filters) supported by the API

### arubaos_set

* Supports check_mode and diff
* Supports normal and mulipart set operations

### CODE REVIEW

**Comment by sachaboudjema** [comment]
Force-pushed minor fixes to arubaos_controller_config.py

**Comment by sachaboudjema** [comment]
Force-pushed updates to module docs

**Comment by alagoutte** [comment]
Nice work !

**Comment by karthikeyan-dhandapani** [comment]
Hi @sachaboudjema,

Thanks for your contribution. This is nice work and brings in all features from the API endpoints mentioned in the automation guide. There are couple of things I would like to discuss.

1. Licensing: You have GNU GPLv3 and we have Apache 2.0 license. Are you comfortable changing the license to Apache 2.0. We would like to understand your thoughts about this.

2. Further improvements: Are you comfortable with us making changes and improvements to the code you contributed?

Thanks,
Karthik

**Comment by sachaboudjema** [comment]
Hi @karthikeyan-dhandapani 

I will change the license to Apache 2.0 and push to the same PR shortly.

From then you can do what you want with the code :)

However, Please give credit for the work done.

**Comment by sachaboudjema** [comment]
License modified

**Comment by karthikeyan-dhandapani** [comment]
> License modified

Thanks again!

**Pull request merged**
